### ISSUE TITLE
Emit warning if the database is not fresh

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/cpan-audit#10]
Taken from @robrwo's suggestion in [Should CPAN::Audit::DB be a separate distro?
](https://github.com/briandfoy/cpan-audit/discussions/7#discussioncomment-3026952).

**Comment by briandfoy** [comment]
This needs a little bit of code to get the current version from MetaCPAN and compare it to the current version. That's means that we'd need to connect to the network, which is a bit of a problem for the idea of CPAN::Audit, which wants to be completely standalone.

We could add some instructions for doing this in a multistep fashion so `cpan-audit` itself does not check the network. It would then be up to the user to decide to do those extra steps, and people who don't want the network access at all don't have to worry about it.

Some security problems with checking the network:

* it's dependent on local name resolution, which means that someone can fake that so you think you have the fresh data
* it's dependent on the source of the version information is the right source. We might be to handle that with hostname cert verification, but we'd have to track what we think that value should be (because it changes). SSL certs are almost completely useless for verifying identify now.

Perhaps better:

* Look at the source on Github and it's GPG signature. If you trust that cert, you trust that version. Even if someone manages to make a fake Github and a fake database, they will have a really hard time faking the GPG signature. They can have some signature, but it won't be for the key that people expect.
* But, how do people trust a GPG key? It's trivial to make any key that you like and submit it to a public keyring using any identifier that you like. Just because it has my email address doesn't mean I made that key. That also goes for anyone who signs my key.
* However, I can individually deal with CPAN::Audit users so they can verify that they know what my key is, they can sign it with their key, and now they know. This is a bit burdensome for everyone to do this, but that's kinda how it goes.

**Comment by robrwo** [comment]
I don't see a need to check the network. Something as simple as checking the current date against of the DB.  If it's more than a 12 weeks out of date, emit a warning.

There should be an option to suppress the warning for cpan-audit on the command line, or even possibly a user configuration preference in a `~/.cpan-audit` configuration file.

There's a lot of things being added regularly as we comb through existing CPAN modules looking for security fixes in the changes.  But I think once we are caught up there may not be updates very often.

**Comment by briandfoy** [comment]
I've added a way for cpan-audit to check freshness. At the moment its optional with the `-f` switch, but could evolve into something else.
