### ISSUE TITLE
missing versions in database generation

### ISSUE THREAD

**Issue by schelcj** [briandfoy/cpan-audit#23]
There are adivsories defined for modules that will not show up when `advistories_for()` is called because there is are versions defined in the DB. [CPAN::Audit::Query::advisories_for](https://github.com/briandfoy/cpan-audit/blob/master/lib/CPAN/Audit/Query.pm#L50) builds the list of advisories from the list of known versions for a given dist. If there there were no versions detected during the database generation then any advisories defined for a dist are never returned. For example, `File::Glob` has advisories defined but the call to [metacpan fastapi](https://github.com/briandfoy/cpan-security-advisory/blob/master/util/generate#L317) is returning nothing. [File::Glob](https://metacpan.org/pod/File::Glob) is clearly in metacpan so I'm not sure what's going on but there are several instances of this happening with the current database.

**Comment by briandfoy** [comment]
If I read this right, I think that you mean that cpan-audit does get a list of versions for a module, so it selects no advisories for that module?

This also might be a MetaCPAN issue.

**Comment by briandfoy** [comment]
Are you checking a really old installation? The only adivsory for File::Glob is for versions lower than 1.13. That was first released with v5.14.2 (v5.15.3 too).

**Comment by schelcj** [comment]
Because `cpan-audit` builds the advisories starting from the versions _and_ the db `util/generate` fails to detect versions no advisories are ever returned. It's kinda both but possibly more a metacpan issue.

Here's the list of dists without a version in the database:
```
$ perl -d -e 42

Loading DB routines from perl5db.pl version 1.55
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(-e:1):   42
                                                                                                                                                                                                 DB<1> use CPAN::Audit;

DB<2> $a = CPAN::Audit->new()

DB<3> x grep {not scalar $a->{db}->{dists}->{$_}->{versions}->@*} keys $a->{db}->{dists}->%*
0  'Spoon-Cookie'
1  'File-Glob'
2  'ePerl'
3  'Batch-BatchRun'
4  'sperl'
5  'Mail-Mailer'
6  'ActivePerl'
7  'Poe-Component-IRC'
8  'MojoX-Dispatcher-Static'
9  'MT'
```

When the generate command is ran to build the database these dists are seeing this response from metacpan `{"took":7,"_shards":{"successful":3,"total":3,"failed":0},"hits":{"max_score":null,"total":0,"hits":[]},"timed_out":false}`.

**Comment by schelcj** [comment]
It appears that the `HTTP::Tiny` POST in [util/generate](https://github.com/briandfoy/cpan-security-advisory/blob/master/util/generate#L317) that metacpan returns no results.

ps: working in 5.30 and 5.36.

**Comment by schelcj** [comment]
Are the module versions even needed if the advisory has the affected and fixed versions?

**Comment by briandfoy** [comment]
For File::Glob it may not matter. But the module version, which we know locally, connects to the distro version, which we need to get from the database. From there, we can look for vulnerabilities in that distro version, which is the version in the reports.

It would seem like we could simply go from the module namespace to the distro, but some modules have moved around. There aren't that many of those, so it a small edge case.

I haven't had time to look at it, but it's next up on my to do list.

**Comment by schelcj** [comment]
Found the root cause and sent PR to fix https://github.com/briandfoy/cpan-security-advisory/pull/101.
