### ISSUE TITLE
Two different DB generate scripts

### ISSUE THREAD

**Issue by schelcj** [briandfoy/cpan-audit#25]
There is `util/generate` in this repo and another `util/generate` in [cpan-security-advisory](https://github.com/briandfoy/cpan-security-advisory). I patched the later in my last PR but not the version in this repo. Which is used to generate database for the distribution for CPAN?

**Comment by schelcj** [comment]
Additionaly, the git submodule in this repo is fixed at a commit from 7/23/2022.

**Comment by briandfoy** [comment]
Eventually cpan-security-advisory will generate the database, but we aren't there yet. Continue to use the one in cpan-audit for now.

When I'm sure all the changes that we've made to cpan-security-advisory are good and that we can generate a good DB, I'll update the submodule. I'm just lacking in some time at the moment.

**Comment by schelcj** [comment]
Would you want a PR for sync the generate scripts or just wait till you have some time to sort out the submodule?

**Comment by briandfoy** [comment]
If it makes it easier, you can send a PR to sync that.

Eventually I'm thinking that CPAN::Audit::DB would be a separate distribution. We can update that separately from CPAN::Audit. That's why things are a bit weird at the moment.

**Comment by schelcj** [comment]
I can wait then, thanks.
