### ISSUE TITLE
Not indexed on CPAN

### ISSUE THREAD

**Issue by oalders** [briandfoy/cpan-audit#38]
It looks like the latest release has disappeared from 02packages. Maybe this dist needs a re-index? https://cpanmeta.grinnz.com/packages?module=CPAN%3A%3AAudit&match_mode=exact

**Comment by bleargh45** [comment]
Ah, that at least explains why I can't find it on MetaCPAN any longer.

**Comment by oalders** [comment]
The latest version can be found here: https://metacpan.org/release/BDFOY/CPAN-Audit-20230104.001

**Comment by briandfoy** [comment]
Well, the latest version is in the GitHub releases page. I'm working on fixing this for CPAN though.

**Comment by briandfoy** [comment]
I've uploaded 20230202.003, and I'll check that this makes it into CPAN.
