### ISSUE TITLE
Mojolicious not listed as a dependency

### ISSUE THREAD

**Issue by garu** [briandfoy/cpan-audit#42]
Hi brian! Hope you're doing well :D 

When trying to run `util/generate`, I bumped into this error:

```
▶ perl util/generate
Can't locate Mojo/Util.pm in @INC
``` 

And, of course, installing `Mojolicious` fixed it. But I haven't written a PR for Makefile.PL because I'm not sure whether `util/generate`'s dependencies should be considered or not.

Cheers!

**Comment by briandfoy** [comment]
Mojolicious is not a dependency of the module, although it is one of the things you need for the repo tools. A person installing the distribution doesn't need Mojo.

**Comment by garu** [comment]
Would a documentation patch mentioning that repo tools dependency be of interest? If so I can send you a PR.

Cheers!

**Comment by briandfoy** [comment]
I'll look at a patch, but I'm not sure where you'd document that.
