### ISSUE TITLE
validate yml reports coming from cpan-security-advisory

### ISSUE THREAD

**Issue by garu** [briandfoy/cpan-audit#44]
Hey brian! While trying to spot inconsistencies on CPAN::Audit::DB's output format, we created a function that looks at the `affected_versions` field and warns when something looks wrong.

It seems quite trivial to convert it to a "private" function that checks entries on the fly when populating DB.pm. Would that interest you? It should help prevent typos on the yaml files.

If so, should that verification be here on cpan-audit or on a script under [cpan-security-advitory](https://github.com/briandfoy/cpan-security-advisory)?

Just let me know and I'll happily send you a PR on the proper repository.

Cheers!

**Comment by briandfoy** [comment]
There are GitHub actions that take care of this.
