### ISSUE TITLE
Why is 'db' an allowed key (CPAN/Audit.pm)

### ISSUE THREAD

**Issue by reneeb** [briandfoy/cpan-audit#53]
Hi brian,

is there a reason why 'db' is an allowed key?

```perl
sub new {
	my( $class, %params ) = @_;

	my @allowed_keys = qw(ascii db exclude exclude_file include_perl interactive no_corelist quiet verbose version);

	my %args = map { $_, $params{$_} } @allowed_keys;
	my $self = bless \%args, $class;

	$self->_handle_exclude_file if $self->{exclude_file};

	$self->{db}       = CPAN::Audit::DB->db;

	$self->{filter}   = CPAN::Audit::Filter->new( exclude => $args{exclude} );
	$self->{query}    = CPAN::Audit::Query->new( db => $self->{db} );
	$self->{discover} = CPAN::Audit::Discover->new( db => $self->{db} );

	return $self;
}
```

`$self->{db}` is set no matter if a param *db* was passed to `new` or not and `_handle_exclude_file` does not use the value either.

**Comment by briandfoy** [comment]
Sorry for the multiple commits there. My git tool had a GIT_AUTHOR_NAME set when I didn't realize it.

**Comment by briandfoy** [comment]
Thinking about this more, this sort of dependency injection might make testing easier.

**Comment by briandfoy** [comment]
Now we can use the db param if it's provided, but it's up the the user to provide the right sort of object.
