### ISSUE TITLE
CPAN::Audit::DB needs to be removed from the dist

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-audit#64]
CPAN::Audit::DB needs to be added as a separate requirement and removed from the distribution.

When installing separate CPANSA::DB module consistency checks from Carton fail because CPAN::Audit can overwrite CPAN::Audit::DB

**Comment by guest20** [comment]
Does specifying `requires CPAN::Audit => undef` as the version in your `cpanfile` fix this?

**Comment by robrwo** [comment]
> Does specifying `requires CPAN::Audit => undef` as the version in your `cpanfile` fix this?

No. It's based on data in `cpanfile.snapshot`

**Comment by guest20** [comment]
Right, you have to run `carton install` instead of `carton install --deployment` if you want carton to update the snapshot

... but won't `carton` also pin the version of `CPAN::Audit::DB`?

**Comment by briandfoy** [comment]
The latest dev release removed CPAN::Audit::DB, and I'll see how that goes with CPAN Testers. Everyone can play with themselves and report any problems they have.

**Comment by briandfoy** [comment]
I'm planning a new release for next week.

**Comment by briandfoy** [comment]
I've released 20241208.001, which now depends on CPANSA::DB for the data.
